version: '3'

services:
  database:
    container_name: 'postgres-db'
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: 'MainDatabase'
      POSTGRES_USER: 'MainUser'
      POSTGRES_PASSWORD: 'dkfjsdofnsofnmno5j84584nknvkIDJFIDOFJODS&&&***&(hjhdfkldf'
      LC_COLLATE: 'C.UTF-8'
      LC_CTYPE: 'C.UTF-8'
      TZ: 'Etc/UTC'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U MainUser -d MainDatabase']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
